#https://docs.spring.io/spring-security/site/docs/5.2.12.RELEASE/reference/html/oauth2.html
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: oauth2-client
            # Never commit it, it should be provided by environment
            client-secret: 55bfbac8-329d-4701-959e-11b74c481cf5
            authorization-grant-type: authorization_code
            # This URI is a Default URI redirect, create by Spring:
            # {baseUrl}/login/oauth2/code/{registrationId}
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
        provider:
          keycloak:
            user-name-attribute: name
            authorization-uri: http://localhost:8888/auth/realms/oauth2-study/protocol/openid-connect/auth
            token-uri: http://localhost:8888/auth/realms/oauth2-study/protocol/openid-connect/token
            user-info-uri: http://localhost:8888/auth/realms/oauth2-study/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8888/auth/realms/oauth2-study/protocol/openid-connect/certs
            issuer-uri: http://localhost:8888/auth/realms/oauth2-study
            end-session-endpoint: http://localhost:8888/auth/realms/oauth2-study/protocol/openid-connect/logout?redirect_uri=http%3A%2F%2Flocalhost%3A8080
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    root: debug
